#pragma once

#include "MG_include.h"

#include "stc/MG_Asset.h"
#include "stc/MG_Audio.h"
#include "stc/MG_Camera.h"
#include "stc/MG_Component.h"
#include "stc/MG_GameData.h"
#include "stc/MG_Instance.h"
#include "stc/MG_Material.h"
#include "stc/MG_Model.h"
#include "stc/MG_Object.h"
#include "stc/MG_RenderData.h"
#include "stc/MG_Scene.h"
#include "stc/MG_Shader.h"
#include "stc/MG_Transform.h"
#include "stc/MG_WindowData.h"

#include "MG_audio.h"
#include "MG_camera.h"
#include "MG_components.h"
#include "MG_debug.h"
#include "MG_file.h"
#include "MG_id.h"
#include "MG_LL.h"
#include "MG_logic.h"
#include "MG_main.h"
#include "MG_model.h"
#include "MG_object.h"
#include "MG_render.h"
#include "MG_scene.h"
#include "MG_shaders.h"
#include "MG_textures.h"
#include "MG_transform.h"
